baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Najib ERRAMI'
theme = ["hello-friend-ng"]


archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

# Metadata mostly used in document's head
description = "ERRAMI Najib"
keywords = "homepage, blog"


[[menu.main]]
name = "Contributions"
url = "contributions"
weight = 2

[[menu.main]]
name = "C++"
url = "code"
weight = 3

[[menu.main]]
name = "Optimization"
url = "optimization"
weight = 3

[params.portrait]
path = "images/najib2.png"


[[params.social]]
name = "github"
url  = "https://github.com/najibprog/"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/najib-errami-2bb1a7197/"


